### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by jerone** [subesokun/atom-project-view#11]
The following error appears when opening Atom without a project:

```
TypeError: Cannot read property 'indexOf' of undefined(…) "TypeError: Cannot read property 'indexOf' of undefined
    at file:///C:/Users/user/.atom/packages/project-view/lib/project-view.coffee:77:15"(anonymous function)
```

Probably checking if `files` exists [here](https://github.com/subesokun/atom-project-view/blob/master/lib/project-view.coffee#L77) solves the issue...

_Atom 1.3.0-beta6
Project-view 0.3.0_

**Comment by subesokun** [comment]
@jerone Thanks for the pointer and I'll add a fix for that. That you ran into this issue means your project root folder is empty or?

**Comment by jerone** [comment]
Steps to reproduce:
1. Open Atom.
2. Right-click project(s) and choose "Remove Project Folder".
3. Open Settings.
4. This creates an empty project called "config".
