### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by kczx3** [subesokun/atom-project-view#13]
I'm not sure if my version of Atom just updated but this is not working all of a sudden.  Version of Atom is 1.5.4.

**Comment by subesokun** [comment]
Just to be sure, try re-installing the package and double check if the package is activated. Without some more information I can't help you really :( ...

**Comment by kczx3** [comment]
Well I'm not sure what happened but the Setting on the package to actually display the path was unchecked for some reason.  I had never adjusted that as when I first installed it, the path simply displayed with no further action necessary.  IDK if the setting is really necessary though as since this is all the package does, someone could just disable or uninstall it if they didn't want to see it.
