### ISSUE TITLE
Display project name in the title bar

### ISSUE THREAD

**Issue by yufanyufan** [subesokun/atom-project-view#14]
When open multiple atom instance, only this can help you find the instance you want.

**Comment by subesokun** [comment]
@yufanyufan Sounds like a great idea :) I'll look into it as soon as I find some time. Feel free to create a PR for it if you want :+1:

**Comment by jolsen71** [comment]
I believe this is related so I'll offer it as an alternative: I use the `custom-window-title` package. 

My title template is:
`<% if (projectName) { %> <%= projectName %> <% } %><% if (gitHead) { %> [ ⛕<%= gitHead %> ] <% } %> <%= fileName %><% if (filePath) { %> - <%= filePath %> <% } %>`
It displays the project name (if one exists) as defined in project manager package and reverts to the first project path if there is no defined project name.

**Comment by subesokun** [comment]
> This project is no longer maintained as Atom and all repositories under Atom will be archived on December 15, 2022. Learn more in the [official announcement](https://github.blog/2022-06-08-sunsetting-atom/). Thank you for your interest in this project and your support!
