### ISSUE TITLE
Customize the project path via regex

### ISSUE THREAD

**Issue by davidcasey** [subesokun/atom-project-view#17]
![project-view](https://cloud.githubusercontent.com/assets/744677/18019625/3d0fea4e-6b9a-11e6-95e7-9e67876e5454.png)
Am I missing something to enable this? When I go to settings, I only see the Display Path and Keybindings checkboxes. No regex inputs. I've tried uninstalling/reinstalling.

Version 0.5.0
Windows 7 Enterprise SP1
64-bit

**Comment by subesokun** [comment]
Hi @davidcasey, sorry this feature is currently only available on the master branch. I was testing it locally and then forgot to release it... I'll prepare a release as soon as I find some time.

**Comment by carromeu** [comment]
I am waiting too... congrats (and thanks) for work!

**Comment by subesokun** [comment]
v0.6.1 with the regex feature has been release now 🎉
