### ISSUE TITLE
Typo (bug?) in the code

### ISSUE THREAD

**Issue by green-coder** [subesokun/atom-project-view#20]
at /lib/project-view.coffee#L92 :

![screen shot 2017-02-11 at 11 29 39 pm](https://cloud.githubusercontent.com/assets/598193/22854941/4b0627e2-f0b2-11e6-8fd0-a2bfe91ec339.png)

`proj` doesn't seem to be defined. Did you mean `project` ?

**Comment by subesokun** [comment]
This is actually a variable I've missed during the last refactoring. I'll fix this one along with the PR of you. Thanks a lot for the code review! I should really add a liner to this package 😄
