### ISSUE TITLE
Project details only showing for one project at a time in tree-view

### ISSUE THREAD

**Issue by ryanjkelly** [subesokun/atom-project-view#22]
If I only open one project in tree-view, the project details show just fine. When I add a 2nd project to tree-view, the first project loses its details. When I open a 3rd project, the first 2 projects have no details. Only the latest project opened in tree-view ever has details.

My workaround for now is to add all the projects I need, and then restart Atom. That seems to reset something to make all projects show their details.

I'm on PC and have the latest stable version (1.15.0) of Atom and the latest version (0.6.2) of `project-view`.

**Comment by subesokun** [comment]
Hi @ryanjkelly, thanks a lot for reporting this issue and I can confirm that bug but can't promise yet a release date for a bugfix. As soon as I'll find some time I'll fix it. Any help would be appreciated :)

**Comment by subesokun** [comment]
v0.6.3 has been released 🎉
