### ISSUE TITLE
Paths disappear if we add or drag&drop a project

### ISSUE THREAD

**Issue by Scritik** [subesokun/atom-project-view#23]
Hi,

If we drag and drop a project in the tree-view, the paths disappear. If we add a folder, all the paths disappear except the new project.

Atom version: 1.19.5.
Project-view version: 0.6.2

**Comment by subesokun** [comment]
Thanks for reporting the bug. For some reason [atom-tree-view-git-status](https://github.com/subesokun/atom-tree-view-git-status) is not affected by this issue so I've to merge in some recent changes from that project. But PR's are welcome :)

**Comment by jpicton** [comment]
This also occurs when removing a project folder. Basically any action that refreshes the tree view pane will remove the project path.

**Comment by jsg2021** [comment]
This should be fixed now.

**Comment by Scritik** [comment]
Thank you very much, it's all good now! 🎉
