### ISSUE TITLE
Request: Add overflow or hover text to show full path that is truncated by narrow width of project pane

### ISSUE THREAD

**Issue by jolsen71** [subesokun/atom-project-view#24]
Thank you for this this package

Long titles/paths are truncated when the project pane is not wide enough to show the entire line. It would be great if the path was available as overflow (ideal) or hover text, so that way the user can view it in its entirety without having to temporarily resize the project panel.

Thanks again

**Comment by subesokun** [comment]
Hi @jolsen71, could you show me a screenshot of a truncated path in your editor and tell me which theme you're using? Normally the text shouldn't get truncated but this depends heavily on the used Atom theme. With the official themes I had no issues so far.

**Comment by jolsen71** [comment]
I'm using "One Dark" theme. I've also tried removing all my stylesheet customizations as well as switching UI theme "Atom Dark" but the described behavior persists for me. Perhaps it is a conflict with another package?

![example](https://user-images.githubusercontent.com/6641548/42137663-12c158a4-7d36-11e8-844a-c8734ce99950.png)

**Comment by subesokun** [comment]
This project is no longer maintained as Atom and all repositories under Atom will be archived on December 15, 2022. Learn more in the [official announcement](https://github.blog/2022-06-08-sunsetting-atom/). Thank you for your interest in this project and your support!
