### ISSUE TITLE
Add autoToggle support

### ISSUE THREAD

**Issue by subesokun** [subesokun/atom-project-view#5]

**Comment by rodrigopmatias** [comment]
could better explain the functionality.

**Comment by subesokun** [comment]
Show Path configuration as been solved already with PR #9 so only autoToggle is missing. With auto toggle I mean that you can set a flag which controls whether you want to "activate" the project-view on startup of the editor or first later manually (see https://github.com/subesokun/atom-tree-view-git-status/issues/14)
