### ISSUE TITLE
Read out the project names from the .atom/projects.cson file generated by 'Project Manager'

### ISSUE THREAD

**Issue by RStrydom** [subesokun/atom-project-view#6]
Read out the project names from the .atom/projects.cson file generated by [Project Manager](https://atom.io/packages/project-manager)

**Comment by subesokun** [comment]
@RStrydom Definitely that would be nice to support and it should be easy doable. I'll have a look on it as soon as I find some time.

**Comment by subesokun** [comment]
@RStrydom Sorry I think I've to cancel this feature. Actually the title stored in the `projects.cson` is the title for a project set and not for a single project.

``` cson
"MyProject":
  title: "MyProject"
  paths: [
    "path/to/some/project"
    "path/to/another/project"
  ]
```

If I'd use now the title as project name for the folder `.../some/project` and `.../another/project` this will be very confusing.

**Comment by RStrydom** [comment]
I see what you are saying, the group property also isn't usable. Will see if I can put in a feature request into Project Manager first to have something like the following structure:

``` cson
"MyProject":
  title: "MyProject"
  paths: [
    "RootFolderName": "path/to/some/project"
    "RootFolderName": "path/to/another/project"
  ]
```

I will re-open this once we have something usable

**Comment by subesokun** [comment]
@RStrydom Thanks, feel free to drop here a link in case you've created a feature request. I'm wondering if a project name per folder basis is a bit out of scope from the project manager (as it manages project sets) but lets see :)

**Comment by subesokun** [comment]
We can re-open this one as soon as there is a solution for the multiple paths per project issue.
